services:
  backend:
    build:
      context: ../backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 123456
      DATABASE_NAME: vacancies_db
    depends_on:
      - db

  frontend:
    build:
      context: ../frontend
      args:
        VITE_API_URL: http://46.62.146.164:8000
    ports:
      - "3001:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: vacancies_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
