name: Backend CI

on:
  pull_request:
    branches: [develop, main]
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"

  push:
    branches: [develop, main]
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"

jobs:
  backend-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm cli

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
