name: Deploy

on:
  push:
    branches: [develop, main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.event.workflow_run.head_branch == 'main' && 'production' || 'stage' }}

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd app

            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

            docker pull ghcr.io/${{ github.repository }}-backend:${{ github.event.workflow_run.head_sha }}
            docker pull ghcr.io/${{ github.repository }}-frontend:${{ github.event.workflow_run.head_sha }}

            docker compose up -d
